services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto-demo-app
    restart: always
    ports:
      - "8090:8090"
    env_file:
      - .env
    environment:
      - GO_ENV=production
    volumes:
      - ./assets:/app/assets